[project]
name = 'DNA-personalized-clarinet'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.genetic-acoustics-analyzer]
path = 'contracts/genetic-acoustics-analyzer.clar'
clarity_version = 3
epoch = 3.1

[contracts.precision-manufacturing-controller]
path = 'contracts/precision-manufacturing-controller.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
